This should fix the ever occurring test failure with duplicate keys (#869)
For example in this [CI run](https://ci.centos.org/job/devtools-almighty-core/1925/console) we experienced this issue (and in many more):

```
--- FAIL: TestRunSearchRepositoryWhiteboxTest (0.03s)
panic: pq: duplicate key value violates unique constraint "work_item_types_pkey" [recovered]
	panic: pq: duplicate key value violates unique constraint "work_item_types_pkey"
```

I found that function `TestRunSearchRepositoryWhiteboxTest` existed twice in the `search` package:

```sh
$ grep "TestRunSearchRepositoryWhiteboxTest" . -r
./search/search_repository_whitebox_test.go:func TestRunSearchRepositoryWhiteboxTest(t *testing.T) {
./search/search_repository_blackbox_test.go:func TestRunSearchRepositoryWhiteboxTest(t *testing.T) {
```

Also, there was a test that wanted to run in parallel but required the database to be present. This is considered bad practice.

See also #819