fixup
controller/space_test.go:85:23: cannot use client (type *http.Client) as type "context".Context in argument to deleteCodebases:

	*http.Client does not implement "context".Context (missing Deadline method)

		have http.deadline() time.Time

		want Deadline() (time.Time, bool)

controller/space_test.go:85:23: cannot use config (type *configuration.Registry) as type *http.Client in argument to deleteCodebases

controller/space_test.go:85:23: cannot use ctx (type "context".Context) as type *configuration.Registry in argument to deleteCodebases