Fix TestRemoteTokensLoaded
This was the error and it seemed like auth was missing.

time="2017-10-12T14:12:30Z" level=error msg="unable to load public keys from remote service" err="Get http://localhost:8089/api/token/keys: dial tcp [::1]:8089: getsockopt: connection refused" file=/tmp/go/src/github.com/fabric8-services/fabric8-wit/token/token.go func=github.com/fabric8-services/fabric8-wit/token.NewManager keys_url="http://localhost:8089/api/token/keys" line=82 pid=15945 pkg=token
--- FAIL: TestRemoteTokensLoaded (0.00s)
	assertions.go:241:

	Error Trace:	token_whitebox_test.go:20

	Error:		Expected nil, but got: unable to load public keys from remote service

FAIL
FAIL	github.com/fabric8-services/fabric8-wit/token	0.014s